# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/partner_gms/sagit/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/partner_gms/sagit

PRODUCT_COPY_FILES += \
    vendor/partner_gms/sagit/proprietary/product/etc/permissions/com.google.android.maps.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.maps.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/permissions/privapp-permissions-google.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/permissions/split-permissions-google.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/split-permissions-google.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/preferred-apps/google.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/preferred-apps/google.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/sysconfig/google-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/sysconfig/google.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/sysconfig/google_build.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google_build.xml \
    vendor/partner_gms/sagit/proprietary/product/etc/sysconfig/nexus.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/nexus.xml

PRODUCT_PACKAGES += \
    Chrome \
    GoogleContactsSyncAdapter \
    GoogleExtShared \
    GoogleTTS \
    Maps \
    Photos \
    PrebuiltGmail \
    YouTube \
    ConfigUpdater \
    GoogleOneTimeInitializer \
    GooglePartnerSetup \
    GoogleServicesFramework \
    Phonesky \
    PrebuiltGmsCore \
    SetupWizard \
    com.google.android.maps \
    com.google.android.media.effects
